title: Математика
email: mateapeeva@gmail.com
description: "Овој блог е наменет за содржини од математика. Отворете и разгледајте се надевам ќе го најдете одговорот на вашето математичко прашање\U0001F600"
baseurl: /matblog
url: ''
github_username: mateapeeva
theme: minima
plugins:
  - jekyll-feed
header_pages:
  - about.markdown